name: cache_ffmpeg

on:
  workflow_dispatch:

jobs:
  cache_ffmpeg:
    name: Running Unit Tests with Gradle
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg
          version: 1.0

      - run: which ffmpeg
