name: Create a release PR

on:
  push:
    branches:
      - release/**
      # - develop

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Check PullRequest Exists
        id: check_pr
        env:
          HEAD_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "TITLE=${branch_name}" >> $GITHUB_OUTPUT
          head_message=$(echo "${HEAD_MESSAGE}" | sed -n -e 1p)
          echo "HEAD_MESSAGE=${head_message}" >> $GITHUB_OUTPUT

      - name: Create a release PR
        run: |
          gh pr create \
            --base main \
            --title "${{ steps.check_pr.outputs.TITLE }}" \
            --body "This is an automated PR created by GitHub Actions."
