name: Inputs test

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      message:
        description: Specify the server to run the job. (
        required: true
        type: string
        default: 'Default input message'

jobs:
  update_average_score:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'default message'
        run: echo "MESSAGE=${{ github.event.inputs.message || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
      - name: Request score/average to update edison-content-dev cache
        run: echo "$MESSAGE"
