name: Inputs test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      message:
        description: Specify the server to run the job. (
        required: true
        type: string
        default: 'Default message'

jobs:
  update_average_score:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Request score/average to update edison-content-dev cache
        run: echo "${{ inputs.message }}"
