name: Inputs test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      fqdn:
        description: Specify the server to run the job. (
        required: true
        type: string
        default: 'stg-edison.peralingo.jp'

jobs:
  update_average_score:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set FQDN
        id: set-fqdn
        env:
          DEFAULT_FQDN: 'dev4-edison.peralingo.jp'
        run: echo "::set-output name=fqdn::${{ github.event.inputs.fqdn || env.DEFAULT_FQDN }}"
      - name: Make a request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://${{ steps.set-fqdn.outputs.fqdn }}/score/average'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "User-Agent": "edison-github-actions"}'
