name: Inputs test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      host:
        description: Specify the server to run the job. (
        required: true
        type: string
        default: 'stg-edison.peralingo.jp'

jobs:
  update_average_score:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set the variables
        env:
          DEFAULT_HOST: 'dev4-edison.peralingo.jp'
          run: echo "MESSAGE=${{ github.event.inputs.host || env.DEFAULT_HOST }}" >> $GITHUB_ENV
      - name: Make a request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://$MESSAGE/score/average'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "User-Agent": "edison-github-actions"}'
