name: Main Workflow

on: [push, workflow_dispatch]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "This is main workflow"

      - uses: actions/checkout@v3

      - name: ids
        id: ids
        run: |
          ids=$(cat ids.text)
          echo "ids=$ids" >> $GITHUB_OUTPUT

      - name: display ids
        id: display-ids
        run: |
          ids=${{ steps.ids.outputs.ids }}
          for id in $ids; do
            echo "id=$id++++" >> $GITHUB_OUTPUT
          done

      - run: echo ${{ steps.display-ids.outputs.id }}
