name: Main Workflow

on: [push, workflow_dispatch]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "This is main workflow"

      - uses: actions/checkout@v3

      - name: output ids
        id: output-ids
        run: |
          ids="id1 id2 id3"
          output=""
          for id in $ids; do
            output+="id=$id++++\n"
          done
          echo "id=$output" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.output-ids.outputs.id }}
