name: Schedule test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Request score/average to update edison-content-dev cache
        run: echo "Scheduled"
