name: Sub workflow

on:
  workflow_run:
    workflows: ['Main workflow']
    types:
      - completed

jobs:
  sub-job:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Display message
        run: echo "This is a sub workflow"

      - name: Display template name
        run: echo "${{ github.event.workflow_run.head_workflow.name }}"
