name: Sub workflow

on:
  workflow_run:
    workflows: ['Main workflow']
    types:
      - completed

jobs:
  sub-job:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Display message
        run: echo "This is a sub workflow"

      - name: Determine name
        id: determine_name
        run: |
          if [ "${{ github.event.workflow_run.name }}" == "Main workflow" ]; then
            echo "::set-output name=name::Main workflow"
          else
            echo "::set-output name=name::Sub workflow"
          fi

      - name: Display name
        run: echo "This workflow is ${{ steps.determine_name.outputs.name }}"
