name: test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        dirs: ["test_1", "test_2"]
    name: test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo 'Test'

      - name: ${{matrix.dirs}}
        run: |
          cd ${{matrix.dirs}}
          cat test.txt
